name = "ParallelTests"
uuid = "757e9349-83cc-4933-b1a7-11cd5acc9c62"
authors = ["Dominique Orban <dominique.orban@gmail.com>"]
version = "0.1.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
